name: search_package
description: A Dart package providing various search algorithms.
version: 0.0.1
homepage: https://github.com/ibragimov05/dart_search_algorithms/tree/main/search_package
repository: https://github.com/ibragimov05/dart_search_algorithms/tree/main/search_package

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.0
